spring:
    profiles:
      active: local

---
spring:
    profiles: local
    kafka:
      template:
        default-topic: library-events
      producer:
        bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
        key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
        value-serializer: org.apache.kafka.common.serialization.StringSerializer
      admin:
          properties:
            bootstarp.servers: localhost:9092, localhost:9093, localhost:9094