spring:
  profiles:
    active: local

---
spring:
  profiles: local
  kafka:
    template:
      default-topic: library-events-04
    producer:
      bootstrap-servers: localhost:9092, localhost:9093, localhost:9094
      key-serializer: org.apache.kafka.common.serialization.IntegerSerializer
      value-serializer: org.apache.kafka.common.serialization.StringSerializer
      properties:
        acks: all
        retries: 10
    admin:
      properties:
        bootstarp.servers: localhost:9092, localhost:9093, localhost:9094


  devtools:
    add-properties: true

springdoc:
  api-docs:
    path: /api-docs
  swagger-ui:
    path: /swagger-ui-custom.html

  springdoc:
    swagger-ui:
      operationsSorter: method



